spring:
  application:
    name: user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
    # 自定义元数据
      my-metadata: 我的元数据
server:
  port: 8079