server:
  port: 8040
spring:
  application:
    name: gateway
eureka:
   client:
      service-url:
        defaultZone: http://localhost:8761/eureka
management:
  security:
    enabled: false
#zuul:
#  routes:
#    user: /user/**
#  CustomFilter:
#      pre:
#        disable: true
#      path: /user/**
#      sentitive-headers: Cookie,Set-Cookie,Authorization
#      url: http://localhost:8079
logging:
  level:
    com.netflix: DEBUG
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 90000
#ribbon:
#  ConnectTimeout: 3000
#  ReadTimeout: 60000
